### ISSUE TITLE
Change application to syncthing-macos base

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-server-macos#10]
The repository at https://github.com/syncthing/syncthing-macos is great. It is liberally licensed (MIT), and has the following:

* An established process to create DMGs
* Integration with Sparkle for auto-updates
* A menu bar item for the application
* Signed executables and DMGs
* CI Processes that are already established
* Better written application code, with support for older versions of macOS
* A menu item that brings up a preferences screen, including an auto-start option

As a result, I'd like to change over this whole repo from my small custom code, to something based on their existing code. We'll likely take out the update code for now (or just comment it out), but use the rest as a better base.

**Comment by dkanada** [comment]
> Integration with Sparkle for auto-updates

I think if we include automatic updates for Windows and macOS they should be handled outside the core and web client, so Sparkle sounds fine for this repository.

**Comment by dkanada** [comment]
@anthonylavado was this completed?

**Comment by anthonylavado** [comment]
@dkanada Whats in the branch is functional and works, but it’s not complete just yet.

**Comment by anthonylavado** [comment]
### Project Status:

**Done**
- [x] Package the latest Jellyfin build for macOS (handled as a build phase script)
- [x] Package the specified FFmpeg and FFprobe (handled as a build phase script)
- [x] Tray app launches with no error
- [x] Extracts embedded Jellyfin & FFmpeg to correct location
- [x] Jellyfin starts in the background
- [x] Launch the Web UI with menu item
- [x] Restart/Quit with menu item
- [x] View logs with menu item
- [x] Display an About window with correct info
- [x] Display a preferences window
- [x] Preferences to have app start at login
- [x] Preference area that shows current server file folder
- [x] Preference button to show data folder and log folder
- [x] Preference area that shows current URL
- [x] Handle restarts correctly (the server doesn't fully exit when given a `SIGKILL`)
- [x] Preference toggle to enable/disable auto web UI launch (currently disabled by hardcoded default)
- [x] Clean up any other unneeded functions from `syncthing-macos` code

---
**To Do**

- [ ] Add CI to build the executable properly, with resource download
- [ ] Add CI to sign the executable
- [ ] Use CI to package a .DMG
- [ ] Use CI to sign the .DMG
- [ ] Script the signing, waiting for result, and stapling ticket for each of the above steps

---
**Rejected**

- [ ] ~~Preferences to select browser to start with (currently uses System Default)~~
- [ ] ~~Kill an existing, orphaned `jellyfin` when launching (to avoid conflicts)~~

---

**Timeline:** Aiming for 10.5 release or shortly thereafter

Progress can be viewed here:
https://github.com/anthonylavado/jellyfin-server-macos/tree/app-conversion

**Comment by anthonylavado** [comment]
Closing this as of #16, creating new issue.
