### ISSUE TITLE
Create an "Uninstaller"

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-server-macos#36]
The current .app places config files in a few separate locations, all of them standard as per XDG Locations (see https://github.com/jellyfin/jellyfin/issues/698).
These folders are typically hidden as macOS hides dot-files by default. We should create an uninstaller that can cleanly delete these.
This could also serve as a basis for a configuration backup/restore tool to assist with #35.

**Comment by brabs27** [comment]
Hi Anthony, I’ve had to uninstall due to issues with android tv app. Which files do I need to delete that adding app to trash doesn’t delete.
Cheers

**Comment by LePips** [comment]
An uninstaller isn't the way to go, we may just have to change the paths to somewhere else. Is that possible with the executable?

**Comment by anthonylavado** [comment]
We can specify every single path with arguments to the executable (like I do for jellyfin-web). The issue is that changing them now would require a migration for all future "upgrades".

**Comment by LePips** [comment]
Good point, but it's a trivial task to check paths, copy, and delete the old ones to migrate.

**Comment by LePips** [comment]
Additionally, I'll be aggregating the contents to `~/Library/Application Support/Jellyfin` so we can just provide a proper `Uninstall` guide in this repo with the step to just delete that folder.

**Comment by anthonylavado** [comment]
Alright, I dig it 🤠👍
