### ISSUE TITLE
Support for Older macOS Versions

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-server-macos#5]
Right now, this has only been tested on macOS 10.14.6, where it appears to work just fine.

Support, if possible, should be added to allow at least one OS back (10.13.x).

**Comment by kodywilson** [comment]
Hi @anthonylavado ! Is this just to verify that it builds and functions properly on Mac 10.13.6?

**Comment by anthonylavado** [comment]
> Hi @anthonylavado ! Is this just to verify that it builds and functions properly on Mac 10.13.6?

@kodywilson I'm actually going to close this one out, mainly because I'm switching out the entire codebase with something else that will have better compatibility. Sorry!
