### ISSUE TITLE
Allow hiding the icon in the menu bar

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-server-macos#56]
Currently the menu bar icon for Jellyfin Server cannot be hidden. Would it be possible to allow this?

I understand that one problem would be that there is then no clickable way to access the server; you have to manually go to `localhost:8096`. Maybe a solution would be that clicking the app icon opens a browser tab to the server?

**Comment by LePips** [comment]
I am saying no, as having a menu bar item for a background service is very standard. 

Also, it would almost be impossible to re-enable? The only way that we can have this functionality is to have the toggle in a macOS application window, which I would only have accessible through said menu bar item. I think adding any other flows upon selecting the app icon would just be unnecessary.

I recommend something like Bartender or [Hidden](https://github.com/dwarvesf/hidden) for menu bar organization.

**Comment by ghost** [comment]
Yeah, you are right. It would just make the whole thing more complex. I'm closing this issue.
