### ISSUE TITLE
Please make it compatible with MacOs 10.15. It works. I am using right now

### ISSUE THREAD

**Issue by marlinhares** [jellyfin/jellyfin-server-macos#74]
So sad when I tried 10.9.1 and it did not opened at my 2012 Retina. Catalina 10.15.

I tried running directly from tar and worked ok.

So I found this repo and **make a dmg package for my own**. Worked perfectly well in Catalina 10.15.
Tested:
- migration my old database from 10.8
- During first run it asked permission to access my external drive with my movies
- DTS / Dolby / DTS HD and True Dolby stream
- 4k stream to my tv
- Content transcoding
- App Menu Bar with options and start at login

All worked perfectly.

PS: to create the dmg package I used a M1 Max with Xcode 15.4

Jellyfin is compatible with old Macs but the dmg package installer is limiting it.

**Comment by gnattu** [comment]
Dotnet 8 officially requires macOS 12+: https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos

We will not support versions earlier than what is officially supported. If you insist to run it, you are on your own.
